python mkdata.py ICDPUB.T_UCP_DISTRICT 100
python mkdata.py ICDPUB.T_UCP_PASSWORD 100
python mkdata.py ICDPUB.T_UCP_STAFFBASICINFO 100
python mkdata.py ICDPUB.T_UCP_STAFFEXTENDINFO 100
python mkdata.py ICDPUB.T_UCP_STAFFMAC 100
python mkdata.py ICDPUB.T_UCP_STAFFRESTRICTINFO 100
python mkdata.py ICDPUB.T_UCP_STAFF_BBOSS_INFO 100

python mkdata.py TBCS.CM_CU_GROUPCUSTSERVCHANNEL 100
python mkdata.py SHANDONG_MOBILE.IM_INV_TELNUM 100
python mkdata.py SHANDONG_MOBILE.IM_INV_TELNUM_LIMIT 100
python mkdata.py SHANDONG_MOBILE.MM_DET_ALERTINFO 100
python mkdata.py TBCS.MM_WK_COMMONWORKLOG 100
python mkdata.py TBCS.MM_WK_WORKLOGEVALUATE 100
python mkdata.py SHANDONG_MOBILE.SA_DB_DICTITEM 100
python mkdata.py SHANDONG_MOBILE.SUBS_PRIVILEGE 100
python mkdata.py SHANDONG_MOBILE.SUBS_PRODUCT 100

python mkdata.py TBCS.CUSTOMER 100
